export default function Head() {
  return (
    <>
      <title>Surge Ryders</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="google-site-verification" content="zOnP1UxJhmZBMnusjudh5HIyOUNS_AUlB12MsUplvuA" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
